const DIACRITICS_REGEX = /[\u0300-\u036F]/gu

const SPACES_REGEX = /\s+/gu
const SPACES_UNDERSCORES_DOTS_SLASHES_REGEX = /[\s_./]+/gu

const DASHES_REGEX = /[-–—]/gu
const CONSECUTIVE_HYPHENS_REGEX = /--+/gu
const LEADING_HYPHENS_REGEX = /^-+/u

const NON_WORD_CHARACTERS_REGEX = /[^\w-]+/gu
const NON_ALPHANUMERIC_REGEX = /[^a-zA-Z0-9]/gu

const LOWERCASE_CHARACTERS_REGEX = /([a-z])/gu
const UPPERCASE_CHARACTERS_REGEX = /([A-Z])/gu
const DIGIT_REGEX = /\d/u

const TRAILING_PUNCTUATION_REGEX = /[.!?]$/u
const TRAILING_HYPHENS_REGEX = /-+$/u
const LEADING_TRAILING_HYPHENS_REGEX = /^-|-$/gu
const TRAILING_MEDIA_FILE_EXTENSIONS_REGEX = /\.(jpg|png|mp4|mp3)$/u

const ORDINAL_AFTER_DIGIT_REGEX = /(?<=\d)(st|nd|rd|th)/gu
const ORDINAL_START_OR_AFTER_DIGIT_REGEX =
    /^(st|nd|rd|th)|(?<=\d)(st|nd|rd|th)/gu

const VIETNAMESE_D_REGEX = /[đĐ]/gu
const VIETNAMESE_D_LOWERCASE_REGEX = /[đ]/gu
const VIETNAMESE_D_UPPERCASE_REGEX = /[Đ]/gu

const RTL_CHAR_REGEX =
    /[\u0590-\u05FF\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/u

const TRIM_PROJECT_SLUG_REGEX = /^projects\//u

export {
    CONSECUTIVE_HYPHENS_REGEX,
    DASHES_REGEX,
    DIACRITICS_REGEX,
    DIGIT_REGEX,
    LEADING_HYPHENS_REGEX,
    LEADING_TRAILING_HYPHENS_REGEX,
    LOWERCASE_CHARACTERS_REGEX,
    NON_ALPHANUMERIC_REGEX,
    NON_WORD_CHARACTERS_REGEX,
    ORDINAL_AFTER_DIGIT_REGEX,
    ORDINAL_START_OR_AFTER_DIGIT_REGEX,
    RTL_CHAR_REGEX,
    SPACES_REGEX,
    SPACES_UNDERSCORES_DOTS_SLASHES_REGEX,
    TRAILING_HYPHENS_REGEX,
    TRAILING_MEDIA_FILE_EXTENSIONS_REGEX,
    TRAILING_PUNCTUATION_REGEX,
    TRIM_PROJECT_SLUG_REGEX,
    UPPERCASE_CHARACTERS_REGEX,
    VIETNAMESE_D_LOWERCASE_REGEX,
    VIETNAMESE_D_REGEX,
    VIETNAMESE_D_UPPERCASE_REGEX
}
