const tailwindVariants = {
    first: "*:first-child",
    last: "*:last-child",
    only: "*:only-child",
    odd: "*:nth-child(odd)",
    even: "*:nth-child(even)",
    "first-of-type": "*:first-of-type",
    "last-of-type": "*:last-of-type",
    "only-of-type": "*:only-of-type",
    visited: "*:visited",
    target: "*:target",
    open: "*:is([open], :popover-open, :open)",
    default: "*:default",
    checked: "*:checked",
    indeterminate: "*:indeterminate",
    "placeholder-shown": "*:placeholder-shown",
    autofill: "*:autofill",
    optional: "*:optional",
    required: "*:required",
    valid: "*:valid",
    invalid: "*:invalid",
    "user-valid": "*:user-valid",
    "user-invalid": "*:user-invalid",
    "in-range": "*:in-range",
    "out-of-range": "*:out-of-range",
    "read-only": "*:read-only",
    empty: "*:empty",
    "focus-within": "*:focus-within",
    focus: "*:focus",
    "focus-visible": "*:focus-visible",
    active: "*:active",
    enabled: "*:enabled",
    disabled: "*:disabled",
    inert: "*:is([inert], [inert] *)",
    ltr: "*:where(*:dir(ltr), [dir='ltr'], [dir='ltr'] *)",
    rtl: "*:where(*:dir(rtl), [dir='rtl'], [dir='rtl'] *)"
}

export default tailwindVariants
